target("filesep")
    set_kind("binary")
    set_languages("c++17", "clatest")
    add_files("filesep.cpp")

target("canonical_demo")
    set_kind("binary")
    set_languages("c++17", "clatest")
    add_files("canonical_demo.cxx", "canonical.cxx")
    add_headerfiles("canonical_demo.hpp")

target("symlink")
    set_kind("binary")
    set_languages("c++17", "clatest")
    add_files("is_symlink.cpp")
